apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: messaging-api
spec:
  encryptedData:
    db: AgAlGGtwAOe3C2p/mzp0h2NAF76bXSAYytdbJUyBWyHz9D84j1o8eeDS/cyX4IHqeAFnA+FfkXuTVz3xj3jkGWE+OU3U/7d/OaSIitYSfqeN13khbKcLbPMseJ7yUHjJ5y8BE/kLHSum+SURcGjzKsUqNWmRt1ptJ2LO+xWKApCWFVkCRJJwrPnVdaXDb3ECdq6v225+VEbzfVo0V9uWe1lmsVcBcfHdKeUeRqx67RSPvpYMCez+QxA8rJIAZq+ytKmjrS7wF6f59114wgvoIr6/117LfIKsB4DDCOM90SDlNXVQIvM64r7ursfIXfmuHs6WQFW2hNpfmg+MTOkkT6F92C5+EkPSnVQ7r5VGQSstf2cVTHILHiIu3UJZBGxgRlQfumwdHCeOhx6d6T7xoMfW95ex0OSbNnNypCWfQxSQ+gWc2AXKuU82REksW9ZV8UaVz2ceu2WVojJHZ5SIFC5VsjP4XKpJ0KDl78zutsDhKD87YvbUsTyPcfoKFZP8PwtapvDQQ8wdvgzFRbjWxvZCUZxIGzyqN08+4mhKL29wkeC6rHuCVCPZQ5/l6pi0y7v1FgfN3jz1sHcHKVJo4Iu5Ph4B4FH9Eq2GOHzOSd0YB07epc8bz/tjlVa3dlSWEGRICyH+eAjF2HfT5SbBPs2tC5wjlW7HjCpoeaHpzeySW/SVFIDn9YZLx2HQzKqhv4g+nSWB8keSFyCdhIeJuy4MYU68e0yKgJF7dbXMEMG0/SIt6BoZIKw19qRb3mIEMrrQbPwZpBZa8cxk3Z3GX8WROwmQQsadtMG1xjkWcbBwPBAd9CX+hGLHsL/M4VTFLddvtR355ESgV0Zb6L7emLPtmqLjzqlkV6C+szbqqCd3+Oh/tnc6lk8NNdB3uqHderlJpU033Gdv6Q==
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: messaging-api

