---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-messaging-api
spec:
  cors:
    origins:
      - https://admin.treetracker.org
      - https://beta-admin.treetracker.org
    headers:
      - Content-Type
      - Authorization
    methods:
      - 'GET, POST, PATCH, PUT, OPTIONS, DELETE'
