apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: messaging-api
spec:
  encryptedData:
    db: AgB5+3WVs1RlJKO/PjDNolccH/Z9m8UuDGaXXMvTvWbBtuM0L0XyL+Ss3vbrCMDwHLrsi+AgIbP0o//uZXNvlIHIoxNOSEvWw5n0Q/zm3uAaZWXF6qmCSWJL6cCYEqZg2z1FTUlMQS0w9JkdyXnOfeskC95T/KQbHbspay4U6px6bS4JvJGFZNFVrjHnHAhvRnGgHeVUgi6ujTg+Eqg1hc4OFqUcVX/mIv+bP/kb06M1jo9URqacrEl+sIsxFC8aTTFZfQZZoiSg8G6qkgY3Cr+fkTyrLPLQ9NdO0QZKSldDVpODhwn2ax/rsH4d7XiI9MpDFz0ZpStMcYGRTgV+4mzvrQD9fuGV8hcBUL8q/7fFzygmN4v1ibIxCLBPU/CHMkbZuS0y7HdSV0L/VNC303NjwMp80ln2PFI3mm0oV5+98ZI8ZfU9owmmeMB5Y0aPsOubo1SS5dobAOnoPORgkiZC4SPuWQknI9ErgGCPSJxRhT9ZG0HZ88TcEGI8abZNY3FJ3nEmuU/clQNZZAcju3uYfd0H1md9ekVVgEJlXhx0RraLeBkJlyxybOy+Sg27QEV0C7C2dnpV7QnbP+pNUCM0kIEmjReddc6k12XyshaCFAGxUS+FIXib7XBPdArccJZXc/xSFoU1L1oozjWUKbMsJxAK3IWq4mgs3wq8z3k1//h8cMOY/haMTvKcp+RVBElwX9uv7Qims+80We2TyV/rpgdLiBULrGexVDKm8kzDQl+xsxI0UsgWfgOwkA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: messaging-api

