apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: messaging-api
spec:
  encryptedData:
    db: AgAKFej+U6rUdMhqhYEAG/n+exYdfqOC+69oBAn6yaY4m4dbKrd4QSG3NOfe7cn+o7h0duNUd/Oi6yG4kB5MJ9u4oVwCYaBQSe3j8CfcFOPMJJP0AFJjXECnDW3SeNLuXZeP+dZsGnZoIvMJL7+vOKIHdM5gp6uQ9qYrhXgIgnjxV3ehXlb5mvx2raCwVmEYvZbB2+QhYHrwj/rUWR832AvpdYAo25LeDrE0JGK4I8Ou0ZroYnpBUU4o5L295H4DWarqD59ib4WHxY8TKk/r29BUodKYV9pM3WjU75CAMRu/wJPpxQgs2t2Zs/IJBT5xuOc2FSzNsKSopSuAOl69kiVwcByBHNw1+jqx75/ECZUaxY3fSUVMrFcr3lfMX2fXPHDvXk45ASZxyYIuFu9rgWRDM2GKhPW40RM9N4V2qITAHyvu2Y4JQJQORvJ7qsUnGIXttgdglAjT4Pd1PRax+dhpk+bZuWkDakY894V3S2zg8K//e+CtLVw8qWbnwGgwh3opADvFOIRmpY/41O3vzdTD14qy2Uq6SWPfIabnmokADS/iGUSz4285qqnr93DbaTXQcFWeBuDRahtYFB30o4a/Tsns4uGoYXpr0Mb07b3O1qkZyye7Ag50PG2Bgc7MtmaWGtBz6JtlByo5tTZwamGw6lK72MOzMEBDrTQUIIiG4zgAWKMGDWxAgesIVJSm4na+yXKD5BAB7dX45ICiPGCosCoGwUADvd+5DK8V8waXR/be+rqAwe2rcW+SwEMnkDOTENbdYEtW7ulLSGjVB2b2tcrpP6X8mD7i3JnzbDPR+bBZYGBy/LtW/Hd0jH9xgLEbXrRYFEpIaUwmsQahpCHTwD/LjpMc12XRWG5ydT8dx+3uIE5S0I6S
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: messaging-api

