---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-connection
  namespace: messaging-api
spec:
  encryptedData:
    db: AgALTfwVVwU0SgAoIZcY2nIRep90tAtDEgIjTk7zFuigJT1H8wW8t6wAgTOff5JFaWwjlwX+PO3LDW3zlrUZQlvvn9t67XX1py9elGWld7PpyuWITYnTgkpe+fWxWvVU6Pomns4qMMGaH0hKdEH16eyPIfjGqDh4GiKFePwuWZy46k+TjW4pY5u6lXjHh3hX48fc1NRO6ta7Hruchhe0debbDknCC2Nvn8rzo1AersyzOZH/8ca3OxHST+UcO51o+JxYLr4mUqJderDaupVeTU9Z0mxqQue2PZVhQJ+Y+0lfRQaXQ+HBc2g2gQjVcmJlGOPc2z2h/CQNrDkfX+H//gf4z6JrK1MMBNpsPeyU1qhJbXbUghAp2F7JXY2RiCoji+FebM2BmSmGgRa1PF3PE5EM8bnysLQiUuDPglAG4Lc1Z/pWKiWm1oHRrUbDWck5BDhdnljQB/k1d3kmn42vu6ETp23WTSX+QxWp8xqZZN0dHWyT5C0yw+JV/HrM7brM1iG4Gr0nykRchkxaMztsqzfBjyID5s7w0QUyuzDX8SUCGS3xluPJ8OEI7FZisBj8DVSsSZnFpeywms2G5HGyiY4SjNyMlm7wh1TaCX5Gr5AM5TJosF6YrSXs9wUYc94lGLl3AmmXKpqXEOWdLZZ7Mwa0wzM+drfH9xLqetrh4COOlmeg990WFnb8IsptTPurxPlItxJ6Xs5qWhc7jDFC09RY44bWgd5366F2YA+/7ZPv1egaIIU+G/tVHBQViP2PDd8BOJdOeRo1lHFOjlUTddhzn5V1vjrzzZjSFr66TR8+6u5k4sDtoeDNnJG/QEWXoSiRpMdBtE7Ftl92E20tisyXrQ2/pqbLwSiifel+OavsOPUcE2DFJChflN1m37eAnBI=
  template:
    metadata:
      name: database-connection
      namespace: messaging-api
