apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-messaging-api
  labels:
    app: treetracker-messaging-api
spec:
  replicas: 1
  containers:
    - name: treetracker-messaging-api
      env:
        - name: NODE_LOG_LEVEL
          value: debug

  
