patchesStrategicMerge:
  - database-connection-sealed-secret.yaml
  - database-migration-connection-sealed-secret.yaml
  - deployment.yaml
  - mapping.yaml
images:
  - name: greenstand/treetracker-messaging-api
    newTag: 1.14.5
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base